apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: objsrv
  name: objsrv
spec:
  replicas: 1
  selector:
    matchLabels:
      app: objsrv
  template:
    metadata:
      labels:
        app: objsrv
    spec:
      containers:
      - image: localhost:32000/os_bin:0.1
        name: objsrv-bin
        ports:
          - containerPort: 4100

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: objsrv
  name: objsrv
spec:
  ports:
  - name: 4100-4100
    port: 4100
    protocol: TCP
    targetPort: 4100
  selector:
    app: objsrv
  type: ClusterIP