---
apiVersion: v1
kind: Namespace
metadata:
  name: noi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: noi-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: microk8s-hostpath

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: objsrv
  name: objsrv
spec:
  replicas: 1
  selector:
    matchLabels:
      app: objsrv
  template:
    metadata:
      labels:
        app: objsrv
    spec:
      containers:
      - image: localhost:32000/os_bin:0.1
        name: objsrv-bin
        ports:
          - containerPort: 4100
        volumeMounts:
          - mountPath: /opt/IBM/tivoli/netcool/omnibus/db 
            name: noidata
      volumes:
        - name: noidata
          persistentVolumeClaim:
            claimName: noi-pvc 

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: objsrv
  name: objsrv
spec:
  ports:
  - name: 4100-4100
    port: 4100
    protocol: TCP
    targetPort: 4100
  selector:
    app: objsrv
  type: ClusterIP


---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: snmp-probe
  name: snmp-probe
spec:
  replicas: 1
  selector:
    matchLabels:
      app: snmp-probe
  template:
    metadata:
      labels:
        app: snmp-probe
    spec:
      containers:
      - image: localhost:32000/snmp_probe_bin:0.1
        name: snmp-probe-bin
        env:
          - name: OS_NAME
            value: "NCOMS"
          - name: OS_SVC_NAME
            value: "objsrv"
          - name: OS_SVC_PORT
            value: "4100"
        ports:
          - containerPort: 1162

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: snmp-probe
  name: snmp-probe
spec:
  ports:
  - name: 1162-1162
    port: 1162
    protocol: UDP
    targetPort: 1162
  selector:
    app: snmp-probe
  type: ClusterIP

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-ingress-udp-microk8s-conf 
  namespace: ingress
data:
  162: "noi/snmp-probe:1162"