---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: nginx-ingress-microk8s-controller
  namespace: ingress
spec:
  selector:
    matchLabels:
      name: nginx-ingress-microk8s
  template:
    metadata:
      labels:
        name: nginx-ingress-microk8s
    spec:
      containers:
      - name: nginx-ingress-microk8s
        ports:
        - name: snmp-trap-udp
          containerPort: 162
          hostPort: 162
          protocol: UDP